### ISSUE TITLE
Feature Request: Add Service To Water By Volume

### ISSUE THREAD

**Issue by peter-dolkens** [Bwooce/ecowitt_iot#3]
The WFC01 supports supplying a specified amount of water before automatically turning off

Would be great to expose this as a service in this integration

I currently achieve this with a `rest_command` as follows:

```yaml

  wfc01_watering_by_volume:
    url: 'http://{{gw}}/parse_quick_cmd_iot'
    method: POST
    content_type: "application/json; charset=utf-8"
    payload: '{"command":[{"on_type":0,"off_type":0,"always_on":0,"on_time":0,"off_time":0,"val_type":3,"val":{{ (litres | int) * 10 }},"cmd":"quick_run","id":{{ id | int }},"model":1}]}'

```
